### ISSUE TITLE
Pre-existing test failures blocking CI (circular imports and regime detection)

### ISSUE THREAD

**Issue by blackms** [blackms/AlphaPulse#191]
## Issue Summary

Pre-existing test failures in CI are blocking PR merges. These failures are **not caused by recent PRs** but exist in the main codebase and need resolution.

### 1. Circular Import in Data Lake Manager
**Location**: `src/alpha_pulse/tests/api/test_*`  
**Error**:
```
ImportError: cannot import name 'DataFormat' from partially initialized module 'alpha_pulse.data_lake.lake_manager'
```

**Root Cause**: Circular dependency between:
- `alpha_pulse.data_lake.lake_manager` imports `DataFormat`
- The import chain creates a circular reference during module initialization

**Impact**: All API tests fail during collection phase

### 2. Feature Integration Tests
**Location**: `test_feature_integration.py`  
**Status**: Collection or execution failures  
**Impact**: Feature engineering tests not running

### 3. Regime Detection Tests
**Location**: `test_hmm_regime_detector.py`  
**Likely Issue**: Missing imports or initialization issues in regime detection module  
**Impact**: Market regime detection tests not running

## CI Impact

**Current CI Status on PRs**:
- ✅ Lint and Code Quality: SUCCESS
- ✅ Security Scanning: SUCCESS
- ✅ Build: SUCCESS
- ✅ Codecov: SUCCESS
- ❌ Test and Coverage: FAILURE
- ❌ Quality Gate Summary: FAILURE

### P0 - Critical (Blocking all PRs)
1. **Fix circular import in lake_manager.py**
   - Use `TYPE_CHECKING` pattern for type hints
   - Move imports inside functions where needed
   - Add lazy loading for cross-dependent modules

### P1 - High (Test coverage gaps)
2. **Fix feature_integration tests**
3. **Fix HMM regime detector tests**

## Verification Steps

After fixes:
```bash
# Test data lake module
PYTHONPATH=. poetry run pytest src/alpha_pulse/tests/api/ -v

# Test feature integration
PYTHONPATH=. poetry run pytest test_feature_integration.py -v

# Test regime detection
PYTHONPATH=. poetry run pytest test_hmm_regime_detector.py -v

# Full test suite
poetry run pytest
```

## Workaround for Current PRs

PRs that are otherwise complete (passing all their own tests, documentation updated, migrations tested) may proceed with merge if:

1. The PR's **own changes** have comprehensive test coverage
2. The PR does **not touch** the failing modules
3. A manual verification shows the PR's tests pass in isolation
4. This issue is referenced in the PR merge commit

## Related PRs

- #190 - RiskManager multi-tenant support (blocked by this issue)

## References

- CI Run with failures: https://github.com/blackms/AlphaPulse/actions/runs/19017325041
- Similar circular import fix: PR #190 (config_loader.py pattern)

---

**Labels**: `bug`, `tests`, `P0`, `blocking-ci`  
**Assignee**: TBD  
**Milestone**: v2.0.0

**Comment by blackms** [comment]
## Circular Import RESOLVED ✅

**PR**: #193

### Fix Applied

Created `src/alpha_pulse/data_lake/types.py` to break circular dependency between `lake_manager.py` and `storage_layers.py`.

**Root Cause**:
```python
# storage_layers.py (line 30)
from alpha_pulse.data_lake.lake_manager import DataFormat  # ← Imports from lake_manager

# lake_manager.py (lines 38-40)
from alpha_pulse.data_lake.storage_layers import (  # ← Imports from storage_layers
    DataLayer, BronzeLayer, SilverLayer, GoldLayer
)
```

**Solution**:
```python
# NEW: types.py
class DataFormat(Enum): ...
class StorageBackend(Enum): ...

# lake_manager.py (updated)
from alpha_pulse.data_lake.types import StorageBackend, DataFormat
from alpha_pulse.data_lake.storage_layers import ...  # No circular dependency

# storage_layers.py (updated)
from alpha_pulse.data_lake.types import DataFormat  # No circular dependency
```

### Verification

**Before (Circular import error)**:
```
ImportError: cannot import name 'DataFormat' from partially initialized module 
'alpha_pulse.data_lake.lake_manager'
```

**After (Circular import resolved)**:
```
ModuleNotFoundError: No module named 'alpha_pulse.data.lineage'
```

The error changed! This proves the circular import is **fixed**. The new error is a **different issue** (missing module).

### Impact

✅ **FIXED**: Circular import between lake_manager and storage_layers
✅ **Backward compatible**: Existing imports still work
✅ **Unblocks**: API tests can proceed past circular import

### Remaining Issues (Separate Bugs)

After fixing the circular import, we discovered **additional import issues**:

1. **Missing module**: `alpha_pulse.data.lineage`
   - Imported by: `data_catalog.py` (line 21)
   - Error: `ModuleNotFoundError: No module named 'alpha_pulse.data.lineage'`
   - **Action**: Create separate PR to add missing module or remove import

2. **Missing dependency**: `aiofiles`
   - Imported by: (TBD - need to trace)
   - Error: `ModuleNotFoundError: No module named 'aiofiles'`
   - **Action**: Add to `pyproject.toml` dependencies

These are **separate from** the circular import and should be fixed in follow-up PRs.

### Next Steps

1. **Merge PR #193** (circular import fix)
2. **Create new issues** for remaining import problems:
   - Issue: Fix missing `alpha_pulse.data.lineage` module
   - Issue: Add missing `aiofiles` dependency
3. **Re-test** API suite after all fixes

### Progress

| Issue | Status | PR |
|-------|--------|-----|
| Circular import (lake_manager ↔ storage_layers) | ✅ FIXED | #193 |
| Missing `alpha_pulse.data.lineage` | ⏳ TODO | - |
| Missing `aiofiles` dependency | ⏳ TODO | - |

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)
